### PR TITLE
fix for non terminanting debounced watcher

### LINKED ISSUE #169: debounced watcher doesn't terminate
This code doesn't terminate: https://github.com/vemoo/notify/blob/a02645e73eb4b0ec3de5ae7774b2a59cf4dc33ca/tests/debounce.rs#L1117-L1125

The issue seems to be with the `WatchTimer` thread not terminating.
I've changed the code here https://github.com/vemoo/notify/commit/a02645e73eb4b0ec3de5ae7774b2a59cf4dc33ca and that way it terminates, but I'm not sure if there's a better way.

### PR DESCRIPTION
**Pull request by vemoo**
fixes #169

### CODE REVIEW

File: src/debounce/timer.rs [hunk 1]
```diff
@@ -70,9 +71,11 @@ impl ScheduleWorker {
                             break;
                         }
                     }
-                }
+                },
+                Action::Stop => return false
             }
         }
+        true
```
Comment (matklad) [inline src/debounce/timer.rs]: Have *zero* idea about what's going on here, but usually channel's closure signifies the same thing as an explicit stop, so I'd expect to see `false` here as well.

Comment (vemoo) [reply src/debounce/timer.rs]: But you can end up there if the channel is empty.
But now that think about it I could have just handled the error case explicitly and return `false` for `Disconnected` and true for `Empty`.
Then on `drop` for `WatchTimer` I just have to drop the sender before the `self.trigger.notify_one();`

Comment (matklad) [reply src/debounce/timer.rs]: >Then on drop for WatchTimer I just have to drop the sender before the 

Again, don't really understand the context, but this seems right to me: it's almost always possible to use "receiver is closed when sender is dropped" instead of an explicit `Stop` event. The benefit is that, after dropping the sender, you have to way to send additional messages.

Comment (vemoo) [reply src/debounce/timer.rs]: It seems it doesn't work, because the `Sender` can't be dropped before `self.trigger.notify_one();` and that needs to happen to avoid a race condition.
